blog/urls.py
from django.urls import path
from blog.views import PostList,DetailView

app_name = 'blog'

urlpatterns = [
    path('blog/', PostList.as_view(), name='blog'),
    path("post/<int:pk>/",DetailView.as_view(), name="single"),
]

core/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('website.urls')),
    path('blog/', include('blog.urls')),   
    path('accounts/', include('accounts.urls')),
    path('products/', include('shop.urls')),
    path('product/', include('product.urls')),

]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

product/urls.py
from django.urls import path
from . import views

app_name = 'product'

urlpatterns = [
    path('product/', views.PostList.as_view(), name='product'),
    path("product/<int:pk>/",views.DetailView.as_view(), name="product-single"),
]

templates/includes/latest-blog.html
{% load static %}
  <!-- Start Blog Area -->
  <section class="blog-area ptb-100">
    <div class="container">
        <div class="section-title">
            <div class="row h-100 align-items-center">
                <div class="col-lg-7 col-md-7">
                    <div class="bar"></div>
                    <h2>وبلاگ</h2>
                    <span>آخرین اخبار صنعت</span>
                </div>

                <div class="col-lg-5 col-md-5 text-right">
                    <a href="{% url 'blog:blog' %}" class="btn btn-primary">نمایش همه</a>
                </div>
            </div>
        </div>
    </div>

    <div class="row m-0">
        <div class="blog-slides owl-carousel owl-theme">
            {% for post in latest_blog %}
            
            <div class="col-lg-12">
                <div class="single-blog-post">
                    <div class="blog-image">
                        <img src="{{post.image.url}}">
                    </div>

                    <div class="blog-post-content">
                        <h3><a href="{% url 'blog:single' pk=post.id %}">{{post.title}}</a></h3>
                        <a href="{% url 'blog:single' pk=post.id %}" class="read-more"><i class="flaticon-back"></i></a>
                    </div>
                </div>
            </div>
            {% endfor %}

        </div>
    </div>
</section>
<!-- End Blog Area -->

templates/includes/latest-products.html
{% load static %}
        <!-- Start Projects Area -->
        <section class="projects-area ptb-100 bg-black">
            <div class="container">
                <div class="section-title">
                    <div class="row h-100 align-items-center">
                        <div class="col-lg-7 col-md-7">
                            <div class="bar"></div>
                            <h2>آخرین پروژه ها</h2>
                            <span>ما با شما بهترین پروژه ها را کار می کنیم</span>
                        </div>

                        <div class="col-lg-5 col-md-5 text-right">
                            <a href="{% url 'product:product' %}" class="btn btn-primary">نمایش همه</a>
                        </div>
                    </div>
                </div>
            </div>

            <div class="row m-0">
                <div class="projects-slides owl-carousel owl-theme">
                    {% for products in latest_products %}
                    
                    <div class="col-lg-12">
                        <div class="single-projects">
                            <img src="{{products.image.url}}" alt="image">

                            <div class="projects-content">
                                <h3><a href="{% url 'product:product-single' pk=products.id %}">{{products.title}}</a></h3>
                            </div>

                            <div class="btn-box">
                                <a href="{% static 'assets/img/project-one.jpg' %}" class="popup-btn"><i class="flaticon-photo-1"></i></a>
                                <a href="#" class="link-btn"><i class="flaticon-chain"></i></a>
                            </div>
                        </div>
                    </div>
                    {% endfor %}

                </div>
            </div>

            <div class="map-image"><img src="{% static 'assets/img/map2.png' %}" alt="map"></div>
        </section>
        <!-- End Projects Area -->

templates/includes/latest_single.html
<div class="widget widget_recent_entries">
  <h3 class="widget-title">
    <span>پست های اخیر</span>
  </h3>

  <ul>
    {% for latest in latest_single %}
    <li>
      <a href="#">
        <img src="{{latest.image.url}}" alt="image" />
      </a>

      <h5><a href="{% url 'blog:single' pk=latest.id %}">{{latest.title}}</a></h5>
      <p class="date">{{ latest.jalali_published_date }}</p>
    </li>
    {% empty %}
    <li>هیچ پستی برای نمایش وجود ندارد.</li>
    {% endfor %}
  </ul>
</div>